create table dly_info (
record_id int(11) unsigned not null comment 'The unique identifier of this record, used for reference.',
CIPOS_0 int(11) comment 'PE confidence interval around POS',
CIPOS_1 int(11) comment 'PE confidence interval around POS',
CIEND_0 int(11) comment 'PE confidence interval around END',
CIEND_1 int(11) comment 'PE confidence interval around END',
PE int(3) comment 'Paired-end support of the structural variant', 
MAPQ int(3) comment 'Median mapping quality of paired-ends',
SR int(3) comment 'Split-read support',
SRQ float comment 'Split-read consensus alignment quality',
CONSENSUS varchar(1000) comment 'Split-read consensus sequence',
CE float comment 'Consensus sequence entropy',
CT varchar(16) comment 'Paired-end signature induced connection type',
SVMETHOD varchar(18) comment 'Type of approach used to detect SV',
primary key(record_id),
foreign key fk_dly_info_record_id(record_id) references records(ID))

create table dly_samples(
sample_id mediumint(8) unsigned not null,
record_id int(11) unsigned not null,
GL_0 float(11) comment 'Log10-scaled genotype likelihoods for RR,RA,AA genotypes',
GL_1 float(11) comment 'Log10-scaled genotype likelihoods for RR,RA,AA genotypes',
GL_2 float(11) comment 'Log10-scaled genotype likelihoods for RR,RA,AA genotypes',
GQ int(11) comment 'Genotype Quality',
FT varchar(10) comment 'Per-sample genotype filter',
RC int(11) comment 'Raw high-quality read counts for the SV',
RCL int(11) comment 'Raw high-quality read counts for the left control region',
RCR int(11) comment 'Raw high-quality read counts for the right control region', 
CN int(11) comment 'Read-depth based copy-number estimate for autosomal sites',
DR int(11) comment '# high-quality reference pairs',
DV int(11) comment '# high-quality variant pairs',
RR int(11) comment '# high-quality reference junction reads',
RV int(11) comment '# high-quality variant junction reads',
primary key(record_id),
foreign key fk_dly_samples_record_id(record_id) references records(ID),
foreign key fk_dly_samples_sample_id(sample_id) references samples(sample_id))