create table LMP_info (
record_id int(11) unsigned not null comment 'The unique identifier of this record, used for reference.',
STRANDS varchar(6) comment 'Strand orientation of the adjacency in BEDPE format (DEL:+-, DUP:-+, INV:++/--)',
CIPOS_0 int(11) comment 'PE confidence interval around POS',
CIPOS_1 int(11) comment 'PE confidence interval around POS',
CIEND_0 int(11) comment 'PE confidence interval around END',
CIEND_1 int(11) comment 'PE confidence interval around END',
CIPOS95_0 int(11) comment 'Confidence interval (95%) around POS for imprecise variants',
CIPOS95_1 int(11) comment 'Confidence interval (95%) around POS for imprecise variants',
CIEND95_0 int(11) comment 'Confidence interval (95%) around END for imprecise variants',
CIEND95_1 int(11) comment 'Confidence interval (95%) around END for imprecise variants',
MATEID varchar(20) comment 'ID of mate breakends',
EVENT int(11) comment 'ID of event associated to breakend',
SECONDARY boolean comment 'Secondary breakend in a multi-line variants',
SU int(11) comment 'Number of pieces of evidence supporting the variant across all samples',
PE int(11) comment 'Paired-end support of the structural variant',
SR int(11) comment 'Number of split reads supporting the variant across all samples',
EV varchar(50) comment 'Type of LUMPY evidence contributing to the variant call',
PRPOS varchar(50) comment 'LUMPY probability curve of the POS breakend',
PREND varchar(50) comment 'LUMPY probability curve of the END breakend',
primary key(record_id),
foreign key fk_dly_info_record_id(record_id) references records(ID))

create table LMP_samples(
individual_id mediumint(8) unsigned not null,
record_id int(11) unsigned not null,
SU int(11) comment 'Number of pieces of evidence supporting the variant',
PE int(11) comment 'Number of paired-end reads supporting the variant',
SR int(11) comment 'Number of split reads supporting the variant',
BD int(11) comment 'Amount of BED evidence supporting the variant',
primary key(record_id),
foreign key fk_dly_samples_record_id(record_id) references records(ID),
foreign key fk_dly_samples_individual_id(individual_id) references individuals(individual_id))